Document: pen
Title: Debian pen Manual
Author: <insert document author here>
Abstract: This manual describes what pen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pen/pen.sgml.gz

Format: postscript
Files: /usr/share/doc/pen/pen.ps.gz

Format: text
Files: /usr/share/doc/pen/pen.text.gz

Format: HTML
Index: /usr/share/doc/pen/html/index.html
Files: /usr/share/doc/pen/html/*.html
